# Generated by Django 4.2.4 on 2023-09-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='слаг')),
                ('content', models.TextField(verbose_name='содержание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='превью блога')),
                ('date', models.DateField(null=True, verbose_name='дата создания')),
                ('sign_of_blog', models.CharField(max_length=100, null=True, verbose_name='признак публикации')),
                ('number_of_views', models.IntegerField(verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ('title',),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_at',
            field=models.DateField(null=True, verbose_name='дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='превью'),
        ),
    ]
