# Generated by Django 4.2.4 on 2023-09-18 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blog_sign_of_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='дата создания'),
        ),
    ]
