# Generated by Django 4.2.4 on 2023-09-18 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(null=True, verbose_name='дата создания'),
        ),
    ]
