# Generated by Django 4.2.4 on 2023-09-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_blog_date_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='number_of_views',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
