# Generated by Django 4.2.4 on 2023-09-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sign_of_blog',
            field=models.BooleanField(default=True, verbose_name='признак публикации'),
        ),
    ]
